env:
  global:
    - CC_TEST_REPORTER_ID=da5f6e599241168ce3957e8e12b6b97d75e60e7dfbc12245d2e0024c6cbe9311
language: ruby
rvm:
  - "2.2.10"
  - "2.3.7"
  - "2.4.4"
  - "2.5.1"
gemfile:
  - gemfiles/activesupport_4_2.gemfile
  - gemfiles/activesupport_5_0.gemfile
  - gemfiles/activesupport_5_1.gemfile
  - gemfiles/activesupport_5_2.gemfile
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT