language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.1"
  - "2.1.2"
  - "2.1.3"
gemfile:
  - gemfiles/activesupport_3_0.gemfile
  - gemfiles/activesupport_3_1.gemfile
  - gemfiles/activesupport_3_2.gemfile
  - gemfiles/activesupport_4_0.gemfile
  - gemfiles/activesupport_4_1.gemfile
addons:
  code_climate:
    repo_token:
      secure: "drMasDnIxU1N0UN/0OvJI+nxaj6IsJsPnreodr2VxP2hCI2uHzybk78q5X7LnQVaPd8BBQiXLqmCx0KkyiTb1GbXO0kS992w4C4wbQBwraWs+Ifd18SCCUTCJ84zS3vgh62sHTv/LlLcPLo9yjkPfHYsprVgkK0HryEYNNmEhI4="